// Code generated by "enumer -type=Region -linecomment -json -trimprefix Region"; DO NOT EDIT.

package azure_cs_sdk

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _RegionName = "SouthAfricaNorthEastAsiaSoutheastAsiaAustraliaEastCentralIndiaJapanEastJapanWestKoreaCentralCanadaCentralCanadaEastNorthEuropeWestEuropeFranceCentralGermanyWestCentralItalyNorthNorwayEastSwedenCentralSwitzerlandNorthSwitzerlandWestUKSouthUKWestUAENorthBrazilSouthQatarCentralCentralUSEastUSEastUS2NorthCentralUSSouthCentralUSWestCentralUSWestUSWestUS2WestUS3"

var _RegionIndex = [...]uint16{0, 16, 24, 37, 50, 62, 71, 80, 92, 105, 115, 126, 136, 149, 167, 177, 187, 200, 216, 231, 238, 244, 252, 263, 275, 284, 290, 297, 311, 325, 338, 344, 351, 358}

const _RegionLowerName = "southafricanortheastasiasoutheastasiaaustraliaeastcentralindiajapaneastjapanwestkoreacentralcanadacentralcanadaeastnortheuropewesteuropefrancecentralgermanywestcentralitalynorthnorwayeastswedencentralswitzerlandnorthswitzerlandwestuksouthukwestuaenorthbrazilsouthqatarcentralcentraluseastuseastus2northcentralussouthcentraluswestcentraluswestuswestus2westus3"

func (i Region) String() string {
	if i < 0 || i >= Region(len(_RegionIndex)-1) {
		return fmt.Sprintf("Region(%d)", i)
	}
	return _RegionName[_RegionIndex[i]:_RegionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RegionNoOp() {
	var x [1]struct{}
	_ = x[RegionSouthAfricaNorth-(0)]
	_ = x[RegionEastAsia-(1)]
	_ = x[RegionSoutheastAsia-(2)]
	_ = x[RegionAustraliaEast-(3)]
	_ = x[RegionCentralIndia-(4)]
	_ = x[RegionJapanEast-(5)]
	_ = x[RegionJapanWest-(6)]
	_ = x[RegionKoreaCentral-(7)]
	_ = x[RegionCanadaCentral-(8)]
	_ = x[RegionCanadaEast-(9)]
	_ = x[RegionNorthEurope-(10)]
	_ = x[RegionWestEurope-(11)]
	_ = x[RegionFranceCentral-(12)]
	_ = x[RegionGermanyWestCentral-(13)]
	_ = x[RegionItalyNorth-(14)]
	_ = x[RegionNorwayEast-(15)]
	_ = x[RegionSwedenCentral-(16)]
	_ = x[RegionSwitzerlandNorth-(17)]
	_ = x[RegionSwitzerlandWest-(18)]
	_ = x[RegionUKSouth-(19)]
	_ = x[RegionUKWest-(20)]
	_ = x[RegionUAENorth-(21)]
	_ = x[RegionBrazilSouth-(22)]
	_ = x[RegionQatarCentral-(23)]
	_ = x[RegionCentralUS-(24)]
	_ = x[RegionEastUS-(25)]
	_ = x[RegionEastUS2-(26)]
	_ = x[RegionNorthCentralUS-(27)]
	_ = x[RegionSouthCentralUS-(28)]
	_ = x[RegionWestCentralUS-(29)]
	_ = x[RegionWestUS-(30)]
	_ = x[RegionWestUS2-(31)]
	_ = x[RegionWestUS3-(32)]
}

var _RegionValues = []Region{RegionSouthAfricaNorth, RegionEastAsia, RegionSoutheastAsia, RegionAustraliaEast, RegionCentralIndia, RegionJapanEast, RegionJapanWest, RegionKoreaCentral, RegionCanadaCentral, RegionCanadaEast, RegionNorthEurope, RegionWestEurope, RegionFranceCentral, RegionGermanyWestCentral, RegionItalyNorth, RegionNorwayEast, RegionSwedenCentral, RegionSwitzerlandNorth, RegionSwitzerlandWest, RegionUKSouth, RegionUKWest, RegionUAENorth, RegionBrazilSouth, RegionQatarCentral, RegionCentralUS, RegionEastUS, RegionEastUS2, RegionNorthCentralUS, RegionSouthCentralUS, RegionWestCentralUS, RegionWestUS, RegionWestUS2, RegionWestUS3}

var _RegionNameToValueMap = map[string]Region{
	_RegionName[0:16]:         RegionSouthAfricaNorth,
	_RegionLowerName[0:16]:    RegionSouthAfricaNorth,
	_RegionName[16:24]:        RegionEastAsia,
	_RegionLowerName[16:24]:   RegionEastAsia,
	_RegionName[24:37]:        RegionSoutheastAsia,
	_RegionLowerName[24:37]:   RegionSoutheastAsia,
	_RegionName[37:50]:        RegionAustraliaEast,
	_RegionLowerName[37:50]:   RegionAustraliaEast,
	_RegionName[50:62]:        RegionCentralIndia,
	_RegionLowerName[50:62]:   RegionCentralIndia,
	_RegionName[62:71]:        RegionJapanEast,
	_RegionLowerName[62:71]:   RegionJapanEast,
	_RegionName[71:80]:        RegionJapanWest,
	_RegionLowerName[71:80]:   RegionJapanWest,
	_RegionName[80:92]:        RegionKoreaCentral,
	_RegionLowerName[80:92]:   RegionKoreaCentral,
	_RegionName[92:105]:       RegionCanadaCentral,
	_RegionLowerName[92:105]:  RegionCanadaCentral,
	_RegionName[105:115]:      RegionCanadaEast,
	_RegionLowerName[105:115]: RegionCanadaEast,
	_RegionName[115:126]:      RegionNorthEurope,
	_RegionLowerName[115:126]: RegionNorthEurope,
	_RegionName[126:136]:      RegionWestEurope,
	_RegionLowerName[126:136]: RegionWestEurope,
	_RegionName[136:149]:      RegionFranceCentral,
	_RegionLowerName[136:149]: RegionFranceCentral,
	_RegionName[149:167]:      RegionGermanyWestCentral,
	_RegionLowerName[149:167]: RegionGermanyWestCentral,
	_RegionName[167:177]:      RegionItalyNorth,
	_RegionLowerName[167:177]: RegionItalyNorth,
	_RegionName[177:187]:      RegionNorwayEast,
	_RegionLowerName[177:187]: RegionNorwayEast,
	_RegionName[187:200]:      RegionSwedenCentral,
	_RegionLowerName[187:200]: RegionSwedenCentral,
	_RegionName[200:216]:      RegionSwitzerlandNorth,
	_RegionLowerName[200:216]: RegionSwitzerlandNorth,
	_RegionName[216:231]:      RegionSwitzerlandWest,
	_RegionLowerName[216:231]: RegionSwitzerlandWest,
	_RegionName[231:238]:      RegionUKSouth,
	_RegionLowerName[231:238]: RegionUKSouth,
	_RegionName[238:244]:      RegionUKWest,
	_RegionLowerName[238:244]: RegionUKWest,
	_RegionName[244:252]:      RegionUAENorth,
	_RegionLowerName[244:252]: RegionUAENorth,
	_RegionName[252:263]:      RegionBrazilSouth,
	_RegionLowerName[252:263]: RegionBrazilSouth,
	_RegionName[263:275]:      RegionQatarCentral,
	_RegionLowerName[263:275]: RegionQatarCentral,
	_RegionName[275:284]:      RegionCentralUS,
	_RegionLowerName[275:284]: RegionCentralUS,
	_RegionName[284:290]:      RegionEastUS,
	_RegionLowerName[284:290]: RegionEastUS,
	_RegionName[290:297]:      RegionEastUS2,
	_RegionLowerName[290:297]: RegionEastUS2,
	_RegionName[297:311]:      RegionNorthCentralUS,
	_RegionLowerName[297:311]: RegionNorthCentralUS,
	_RegionName[311:325]:      RegionSouthCentralUS,
	_RegionLowerName[311:325]: RegionSouthCentralUS,
	_RegionName[325:338]:      RegionWestCentralUS,
	_RegionLowerName[325:338]: RegionWestCentralUS,
	_RegionName[338:344]:      RegionWestUS,
	_RegionLowerName[338:344]: RegionWestUS,
	_RegionName[344:351]:      RegionWestUS2,
	_RegionLowerName[344:351]: RegionWestUS2,
	_RegionName[351:358]:      RegionWestUS3,
	_RegionLowerName[351:358]: RegionWestUS3,
}

var _RegionNames = []string{
	_RegionName[0:16],
	_RegionName[16:24],
	_RegionName[24:37],
	_RegionName[37:50],
	_RegionName[50:62],
	_RegionName[62:71],
	_RegionName[71:80],
	_RegionName[80:92],
	_RegionName[92:105],
	_RegionName[105:115],
	_RegionName[115:126],
	_RegionName[126:136],
	_RegionName[136:149],
	_RegionName[149:167],
	_RegionName[167:177],
	_RegionName[177:187],
	_RegionName[187:200],
	_RegionName[200:216],
	_RegionName[216:231],
	_RegionName[231:238],
	_RegionName[238:244],
	_RegionName[244:252],
	_RegionName[252:263],
	_RegionName[263:275],
	_RegionName[275:284],
	_RegionName[284:290],
	_RegionName[290:297],
	_RegionName[297:311],
	_RegionName[311:325],
	_RegionName[325:338],
	_RegionName[338:344],
	_RegionName[344:351],
	_RegionName[351:358],
}

// RegionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RegionString(s string) (Region, error) {
	if val, ok := _RegionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RegionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Region values", s)
}

// RegionValues returns all values of the enum
func RegionValues() []Region {
	return _RegionValues
}

// RegionStrings returns a slice of all String values of the enum
func RegionStrings() []string {
	strs := make([]string, len(_RegionNames))
	copy(strs, _RegionNames)
	return strs
}

// IsARegion returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Region) IsARegion() bool {
	for _, v := range _RegionValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Region
func (i Region) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Region
func (i *Region) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Region should be a string, got %s", data)
	}

	var err error
	*i, err = RegionString(s)
	return err
}
